spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

server:
  servlet:
    context-path: "/api"
xrpl:
  addresses:
    clientUrl: "https://hooks-testnet-v2.xrpl-labs.com/"
    faucetUrl: "https://hooks-testnet-v2.xrpl-labs.com"


