spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

server:
  servlet:
    context-path: "/api"
xrpl:
  addresses:
    clientUrl: "https://s.devnet.rippletest.net:51234/"
    faucetUrl: "https://faucet.devnet.rippletest.net"

